src/SZ.AutoClassics.Site/Controllers/AnuncioController.cs
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SZ.AutoClassics.Aplicacao.Interface;
using SZ.AutoClassics.Aplicacao.ViewModels;
using SZ.AutoClassics.Aplicacao.ViewObjects;

namespace SZ.AutoClassics.Site.Controllers;

public class AnuncioController : Controller
{
	private readonly IAnuncioAppService _anuncioAppService;
	private readonly IEstadoAppService _estadoAppService;
	private readonly ICidadeAppService _cidadeAppService;
	private readonly IAccountAppService _accountAppService;

	private const int REGISTROS_POR_PAGINA = 20;
	public AnuncioController(IAnuncioAppService anuncioAppService,
							 IEstadoAppService estadoAppService,
							 ICidadeAppService cidadeAppService,
							 IAccountAppService accountAppService)
	{
		_anuncioAppService = anuncioAppService;
		_estadoAppService = estadoAppService;
		_cidadeAppService = cidadeAppService;
		_accountAppService = accountAppService;
	}

	public async Task<IActionResult> Index(int pagina, FiltrosAnunciosViewObject filtros)
	{
		filtros.Pagina = pagina > 0 ? pagina : 0;

		var anunciosFiltrosViewObject = new AnunciosFiltrosViewObject();
		anunciosFiltrosViewObject.Anuncios = await _anuncioAppService.ObterTodosPaginado(filtros.Pagina, REGISTROS_POR_PAGINA);
		anunciosFiltrosViewObject.Filtros = filtros;

		return View(anunciosFiltrosViewObject);
	}

	[HttpGet]
	[Authorize]
	public IActionResult CriarAnuncio()
	{
		var anuncioViewModel = new AnuncioViewModel();
		anuncioViewModel.Estados = _estadoAppService.ObterTodos().Result.OrderBy(p => p.UF);
		anuncioViewModel.Cidades = new List<CidadeViewModel>();
		anuncioViewModel.UsuarioId = _accountAppService.ObterUsuarioLogadoId(User);

		return View(anuncioViewModel);
	}

	[HttpPost]
	[Authorize]
	public async Task<IActionResult> CriarAnuncio(AnuncioViewModel anuncioViewModel)
	{
		if (!ModelState.IsValid)
		{
			anuncioViewModel.Estados = _estadoAppService.ObterTodos().Result.OrderBy(p => p.UF);
			anuncioViewModel.Cidades = new List<CidadeViewModel>();
			anuncioViewModel.UsuarioId = _accountAppService.ObterUsuarioLogadoId(User);

			return View(anuncioViewModel);
		}

		anuncioViewModel.ImagemUrl = UploadArquivo(anuncioViewModel.Imagens);

		anuncioViewModel = await _anuncioAppService.Adicionar(anuncioViewModel);

		if (!anuncioViewModel.ValidationResult.IsValid)
		{
			AdicionarErrosNaModelState(anuncioViewModel.ValidationResult.Errors);
			anuncioViewModel.Estados = _estadoAppService.ObterTodos().Result.OrderBy(p => p.UF);
			anuncioViewModel.Cidades = new List<CidadeViewModel>();
			anuncioViewModel.UsuarioId = _accountAppService.ObterUsuarioLogadoId(User);

			return View(anuncioViewModel);
		}

		return RedirectToAction("Index");
	}

	[HttpGet]
	public async Task<IActionResult> AnuncioDetalhes(Guid id)
	{
		if (id == Guid.Empty)
		{
			ModelState.AddModelError(String.Empty, "Não foi possível encontrar nenhum anúncio.");

			return View("Validacao", ModelState.Values.SelectMany(m => m.Errors)
													  .Select(e => e.ErrorMessage)
													  .ToList());
		}
		var anuncioViewModel = await _anuncioAppService.ObterAnuncioDetalhado(id);
		VerificarSeAnuncioEhValido(anuncioViewModel);
		ViewBag.UsuarioLogadoId = _accountAppService.ObterUsuarioLogadoId(User);

		if (!ModelState.IsValid)
			return View("Validacao", ModelState.Values.SelectMany(m => m.Errors)
													  .Select(e => e.ErrorMessage)
													  .ToList());

		return View(anuncioViewModel);
	}
	[HttpGet]
	[Authorize]
	public async Task<IActionResult> Editar(Guid id)
	{
		if (id == Guid.Empty)
			ModelState.AddModelError(string.Empty, "Ops... Não encontramos este anúncio :(");
		var anuncioViewModel = await _anuncioAppService.ObterPorId(id);
		anuncioViewModel.Estados = _estadoAppService.ObterTodos().Result.OrderBy(p => p.UF);
		anuncioViewModel.Cidades = _cidadeAppService.ObterTodos().Result.Where(p => p.Id == anuncioViewModel.CidadeId);

		if (anuncioViewModel == null)
			ModelState.AddModelError(string.Empty, "Ops... Não encontramos este anúncio :(");

		return View(anuncioViewModel);
	}

	[HttpPost]
	[Authorize]
	public async Task<IActionResult> Editar(Guid id, AnuncioViewModel anuncioEditadoViewModel)
	{
		if (id != anuncioEditadoViewModel.Id) return NotFound();

		if (!ModelState.IsValid)
		{
			anuncioEditadoViewModel.Estados = _estadoAppService.ObterTodos().Result.OrderBy(p => p.UF);
			return View(anuncioEditadoViewModel);
		}

		if (anuncioEditadoViewModel.Imagens != null)
		{
			anuncioEditadoViewModel.ImagemUrl = UploadArquivo(anuncioEditadoViewModel.Imagens);
		}

		var anuncioEditado = await _anuncioAppService.Atualizar(anuncioEditadoViewModel);

		if (!anuncioEditado.ValidationResult.IsValid)
		{
			AdicionarErrosNaModelState(anuncioEditado.ValidationResult.Errors);
			anuncioEditado = PopularAnuncioViewModel(anuncioEditado);
			return View(anuncioEditado);
		}

		anuncioEditado = PopularAnuncioViewModel(anuncioEditado);
		return View(anuncioEditado);
	}

	[Authorize]
	[HttpPost]
	public async Task<IActionResult> Excluir(Guid id)
	{
		if (id == Guid.Empty) return NotFound();

		await _anuncioAppService.Excluir(id, User);

		return RedirectToAction("Index");
	}

	[Authorize]
	public async Task<IActionResult> MeusAnuncios(int pagina, FiltrosAnunciosViewObject filtros)
	{
		filtros.Pagina = pagina > 0 ? pagina : 0;
		var anunciosFiltrosViewObject = new AnunciosFiltrosViewObject();
		anunciosFiltrosViewObject.Anuncios = _anuncioAppService.ObterAnunciosPorUsuarioId(_accountAppService.ObterUsuarioLogadoId(User), pagina, REGISTROS_POR_PAGINA);
		anunciosFiltrosViewObject.Filtros = filtros;

		return View(anunciosFiltrosViewObject);
	}

	private string UploadArquivo(List<IFormFile> arquivos)
	{
		var imagens = string.Empty;
		foreach (var arquivo in arquivos)
		{
			var imgPrefixo = Guid.NewGuid() + "_";

			if (arquivo.Length <= 0)
			{
				ModelState.AddModelError(string.Empty, "Nenhuma imagem selecionada");
				return string.Empty;
			}

			var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", imgPrefixo + arquivo.FileName);

			if (System.IO.File.Exists(path))
			{
				ModelState.AddModelError(string.Empty, "Já existe um arquivo com este nome!");
				return string.Empty;
			}

			using (var stream = new FileStream(path, FileMode.Create))
			{
				arquivo.CopyTo(stream);
			}

			imagens += imgPrefixo + arquivo.FileName + ";";
		}

		return imagens;
	}

	[HttpGet]
	public IActionResult ObterCidadesPorEstadoId(string estadoId)
	{
		var cidades = _cidadeAppService.ObterCidadesPorEstadoId(Guid.Parse(estadoId)).Result;

		return Json(new SelectList(cidades, "Id", "Descricao"));
	}

	private void VerificarSeAnuncioEhValido(AnuncioViewModel anuncioVM)
	{
		if (anuncioVM == null)
			ModelState.AddModelError(String.Empty, "O anúncio não existe.");

		if (!anuncioVM.Ativo)
			ModelState.AddModelError(String.Empty, "Este anúncio não está mais ativo.");
	}

	private void AdicionarErrosNaModelState(List<ValidationFailure> erros)
	{
		foreach (var erro in erros)
			ModelState.AddModelError(string.Empty, erro.ErrorMessage);
	}

	private AnuncioViewModel PopularAnuncioViewModel(AnuncioViewModel anuncioViewModel)
	{
		anuncioViewModel.Estados = _estadoAppService.ObterTodos().Result.OrderBy(p => p.UF);
		anuncioViewModel.Cidades = _cidadeAppService.ObterTodos().Result.Where(p => p.Id == anuncioViewModel.CidadeId);

		return anuncioViewModel;
	}
}

src/SZ.AutoClassics.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoClassics</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SZ.AutoClassics.Site.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-gauge-high"></i> AutoClassics</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Anuncio" asp-action="Index">Anúncios</a>
                        </li>
                        @await Html.PartialAsync("_LoginPartial")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AutoClassics
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/filtrosAnuncios.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/sideBar.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/d05f4d26cd.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/toastr@2.1.4/build/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>